name: Continuous Integration

on:
  push:
    branches-ignore:
      - "main"

jobs:
  create-virtualenv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.1"
          architecture: "x64"
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: Pipfile.lock
      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - run: |
          python -m pip install pipenv
          pipenv install --dev
